modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="boku-no-heroes-united"
version="${file.jarVersion}"
displayName="Boku No Heroes United"
authors=["Gillygogs", "Redstoneguy129"]
description='''
Gillygogs My Hero Academia Mod.
'''

[[dependencies.boku-no-heroes-united]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boku-no-heroes-united]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
